# Generated by Django 4.1 on 2022-10-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="upload/image")),
                ("product_name", models.CharField(max_length=30)),
                ("price", models.IntegerField(default=0)),
                ("original_price", models.IntegerField(default=0)),
            ],
        ),
    ]
